"""create weight_entries, body_measurements tables

Revision ID: 28128aaec6b3
Revises: 6b27464f8fb2
Create Date: 2026-07-19 12:22:11.460005

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '28128aaec6b3'
down_revision: Union[str, Sequence[str], None] = '6b27464f8fb2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('body_measurements',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('recorded_at', sa.Date(), nullable=False),
    sa.Column('neck_cm', sa.Numeric(precision=5, scale=1), nullable=True),
    sa.Column('chest_cm', sa.Numeric(precision=5, scale=1), nullable=True),
    sa.Column('waist_cm', sa.Numeric(precision=5, scale=1), nullable=True),
    sa.Column('navel_cm', sa.Numeric(precision=5, scale=1), nullable=True),
    sa.Column('hips_cm', sa.Numeric(precision=5, scale=1), nullable=True),
    sa.Column('left_arm_cm', sa.Numeric(precision=5, scale=1), nullable=True),
    sa.Column('right_arm_cm', sa.Numeric(precision=5, scale=1), nullable=True),
    sa.Column('left_thigh_cm', sa.Numeric(precision=5, scale=1), nullable=True),
    sa.Column('right_thigh_cm', sa.Numeric(precision=5, scale=1), nullable=True),
    sa.Column('left_calf_cm', sa.Numeric(precision=5, scale=1), nullable=True),
    sa.Column('right_calf_cm', sa.Numeric(precision=5, scale=1), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_body_measurements_user_id'), 'body_measurements', ['user_id'], unique=False)
    op.create_table('weight_entries',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('weight_kg', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('recorded_at', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_weight_entries_user_id'), 'weight_entries', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_weight_entries_user_id'), table_name='weight_entries')
    op.drop_table('weight_entries')
    op.drop_index(op.f('ix_body_measurements_user_id'), table_name='body_measurements')
    op.drop_table('body_measurements')
    # ### end Alembic commands ###
