"""create workout_sessions, logged_sets tables

Revision ID: 6b27464f8fb2
Revises: dd991deeca86
Create Date: 2026-07-19 12:09:24.549721

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6b27464f8fb2'
down_revision: Union[str, Sequence[str], None] = 'dd991deeca86'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workout_sessions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('template_id', sa.Uuid(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['template_id'], ['workout_templates.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workout_sessions_template_id'), 'workout_sessions', ['template_id'], unique=False)
    op.create_index(op.f('ix_workout_sessions_user_id'), 'workout_sessions', ['user_id'], unique=False)
    op.create_table('logged_sets',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('session_id', sa.Uuid(), nullable=False),
    sa.Column('exercise_id', sa.String(length=64), nullable=False),
    sa.Column('exercise_name', sa.String(length=200), nullable=False),
    sa.Column('exercise_image_url', sa.String(length=500), nullable=True),
    sa.Column('set_number', sa.Integer(), nullable=False),
    sa.Column('weight', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('reps', sa.Integer(), nullable=False),
    sa.Column('logged_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['workout_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_logged_sets_session_id'), 'logged_sets', ['session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_logged_sets_session_id'), table_name='logged_sets')
    op.drop_table('logged_sets')
    op.drop_index(op.f('ix_workout_sessions_user_id'), table_name='workout_sessions')
    op.drop_index(op.f('ix_workout_sessions_template_id'), table_name='workout_sessions')
    op.drop_table('workout_sessions')
    # ### end Alembic commands ###
