"""create mood_entries table

Revision ID: b757002e90c4
Revises: 28128aaec6b3
Create Date: 2026-07-19 14:59:29.837552

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b757002e90c4'
down_revision: Union[str, Sequence[str], None] = '28128aaec6b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mood_entries',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('moods', postgresql.ARRAY(sa.Enum('JOYFUL', 'PEACEFUL', 'HOPEFUL', 'ENERGETIC', 'CONFIDENT', 'NOSTALGIC', 'CONTEMPLATIVE', 'INSPIRED', 'RELIEVED', 'CURIOUS', 'ANXIOUS', 'FRUSTRATED', 'GLOOMY', 'TENSE', 'IRRITABLE', name='mood_tag')), nullable=False),
    sa.Column('note', sa.String(length=1000), nullable=True),
    sa.Column('recorded_at', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'recorded_at', name='uq_mood_entries_user_date')
    )
    op.create_index(op.f('ix_mood_entries_user_id'), 'mood_entries', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_mood_entries_user_id'), table_name='mood_entries')
    op.drop_table('mood_entries')
    # ### end Alembic commands ###
